app = "dbaronx-api-r2-qjq"
primary_region = "sin"

[env]
  NODE_ENV = "production"
  HOST = "0.0.0.0"
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
